### ISSUE TITLE
No drops at certain elevation

### ISSUE THREAD

**Issue by ghost** [Zamirathe/ZaupFeast#18]
So if a feast with animation is flying over a high snow biome that is ~ 0.70 height in editor the loot just doesn't drop (spawns chutes underground) could we edit plane spawn height or drops height?

**Comment by cyris69** [comment]
Could I edit the Z axis in the code and compile to make the drops spawn down from a high altitude?

**Comment by cyris69** [comment]
like pos.y=200 default and just make it 300 and then the plain effect does pos.y + 50 as normal

**Comment by cyris69** [comment]
nvm i compiled my own fixes.

**Comment by ghost** [comment]
fixed myself
