### ISSUE TITLE
Items drops in wrong places.

### ISSUE THREAD

**Issue by Nicholaiii** [Zamirathe/ZaupFeast#3]
Whenever there is a feast, the item's dropped will not be selected by location. 
The plugin selects a random location in the list, and then drops the configured number items, selected randomly from the whole list, not considering locations specified by that specific item.

Here is my full config:
http://pastebin.com/BXMZfcfw

**Comment by Nicholaiii** [comment]
I wanted to test if the config was loaded correctly into the plugin so I ran this code

```
foreach (FeastItem item in Feast.instance.items)
            {
                Logger.Log("> Item: " + item.Name);
                Logger.Log("> Locations:");
                foreach (string location in item.Location)
                {
                    Logger.Log(">> " + location);  
                }
                System.Threading.Thread.Sleep(250);
            }
```

And it output everything as expected.

I then took a look at the code where it adds the items and found the culprit:
`if (current.Location.Contains(feast.nextLocation.Name()) || !current.Location.Contains("all") || !current.Location.Contains("All"))`
- It adds the items if current.Location does NOT contain All. After changing the code, the feast works as expected. I added this change to the pull request i've submitted.

**Comment by Zamirathe** [comment]
This will be fixed in the new version.
