### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Solenus** [Zamirathe/ZaupFeast#8]
When I start up my server, I get this. Currently we're running only your plugin, on a custom map. Our feast table has a few workshop items in it.

```
Loading Feast 3.0.0.0...........................................................

     Loading 2 translations
     Loading 0 RocketPlayerComponents
     + /runfeast - Immediately starts the feast
         Alias: /frun
Failed to load ZaupFeast, unloading now... :System.NullReferenceException: Objec
t reference not set to an instance of an object
  at ZaupFeast.Feast.Load () [0x00000] in <filename unknown>:0
  at Rocket.Unturned.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename u
nknown>:0

Done............................................................................
```

**Comment by Solenus** [comment]
When I use a default config file it all seems to work so I guess it's an issue with an item from workshop content... but it all worked fine until recently, and none of our workshop items have been updated since before your last 2-3 builds, so I'm not sure why they'd just stop working.

**Comment by Zamirathe** [comment]
Could be an issue with the xml file itself once modified, workshop items not being recognized, locations misspellings...

**Comment by Solenus** [comment]
The previous issue was a broken workshop item, I just forgot to come comment about it here.

There's some chatter about this on your plugin page, but instead of a message telling you where the feast is going in X minutes, everyone's just getting the server printing "coming_feast_msg".

Also, in previous versions there was functionality to have your own custom feast message, but since you added skydrop, I can't figure out how to add in a custom message.
